config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :users
  resources :products
  resources :sessions
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :product_image
  belongs_to :category
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :roles

  def admin?
    @admin ||= roles.find_by(name: 'admin')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include RailsWarden::Authentication
  helper_method :current_user
  helper_method :admin?

  def current_user
    user
  end

  def admin?
    current_user&.admin?
  end

  def redirect_if_not_admin
    redirect_to root_path unless admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def remove
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :redirect_if_not_admin, only: %i[new create destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(require_params)
    redirect_to @product if @product.save
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: 'Product was successfully deleted.'
  end

  private

  def require_params
    params.require(:product).permit(:name, :price, :stock, :description, :category_id, :product_image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = warden.authenticate
    if user
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:alert] = warden.message
      render 'new'
    end
  end

  def destroy
    warden.logout
    redirect_to root_url, notice: 'Logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.roles << Role.second
    redirect_to @user if @user.save
  end

  private

  def user_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.haml
%h1 Categories#index
%p Find me in app/views/categories/index.html.haml

app/views/categories/new.html.haml
%h1 Categories#new
%p Find me in app/views/categories/new.html.haml

app/views/categories/remove.html.haml
%h1 Categories#remove
%p Find me in app/views/categories/remove.html.haml

app/views/categories/show.html.haml
%h1 Categories#show
%p Find me in app/views/categories/show.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TiendaHW
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .login
      - if current_user
        %p
          Logged in as #{current_user.email}. #{link_to "Log Out", logout_path}
      - else
        %p
          = link_to "Sign Up", signup_path
          \#{link_to "Log In", login_path}
    = yield

app/views/products/create.html.haml
%h1 Products#create
%p Find me in app/views/products/create.html.erb

app/views/products/index.html.haml
%h1
  Products
.products
  - @products.each do |product|
    .product
      %p
        = product.name
      %p
        = image_tag product.product_image.variant(resize_to_limit: [100,100])
      %p
        = '$ ' + product.price
      %p
        = link_to 'Show' ,product_path(product)
%br
- if admin?
  = link_to 'New', new_product_path

app/views/products/new.html.haml
%h1 Products
= form_with(model: @product, local: true) do |form|
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :price
    = form.text_field :price
  .field
    = form.label :stock
    = form.text_field :stock
  .field
    = form.label :description
    = form.text_area :description
  .field
    = form.collection_select :category_id, Category.order(:name), :id, :name
  .field
    = form.file_field :product_image
  .action
    = form.submit

app/views/products/remove.html.haml
%h1 Products#remove
%p Find me in app/views/products/remove.html.erb

app/views/products/show.html.haml
.product-display
  %h1
    = @product.name
  %p.image
    #{image_tag @product.product_image.variant(resize_to_limit:[200,200])}
  %p
    description: #{@product.description}
  .stock_price_box
    .price
      %p 
        price: #{@product.price}
    .stock
      %p 
        Disponibilidad: #{@product.stock}
= link_to 'back' , products_path
- if admin?
  = link_to 'destroy', @product, method: :delete, data: {confirm: 'Are you sure?'}

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/index.html.haml
%h1 Users
- @users.each do |user|
  = user.name
  = user.last_name
  = user.email
  %br

app/views/users/new.html.haml
%h1 Sign up

= form_with(model: @user, local: true) do |form|
  .field
    = form.text_field :name, placeholder: "Name"
  .field
    = form.text_field :last_name, placeholder: "Last name"
  .field
    = form.text_field :email, placeholder: "Email"
  .field
    = form.password_field :password, placeholder: "Password"
  .field
    = form.password_field :password_confirmation, placeholder: "Password confirmation"
  .action
    = form.submit

app/views/users/show.html.haml
%h1= @user.name
%p #{@user.email}